openapi: 3.0.0
info:
  title: Get Transfer
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /get-transfer:
    post:
      summary: get transfer
      tags:
        - get-transfer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                example-1:
                  value:
                    data:
                      id: 936f122d-3a66-4460-b0f4-a8f538d00777
                      type: transfer
                      attributes:
                        created_at: '2020-05-13T03:33:57Z'
                        updated_at: '2020-05-13T03:33:57Z'
                        destination_account_number: bongloy_testing-P01-1234560
                        destination_account_holder_name: null
                        currency: USD
                        status: failed
                        metadata:
                          foobar: foobar
                        error_code: destination_account_not_found
                        error_message: Destination account not found
                        amount: 10000
      operationId: post-get-transfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                transfer_id:
                  type: string
            examples:
              example-1:
                value:
                  transfer_id: 936f122d-3a66-4460-b0f4-a8f538d00777
              example-2: {}
        description: ''
    parameters: []
  /list-all-transaction:
    post:
      summary: List All transaction
      tags: []
      responses: {}
      operationId: post-list-all-transaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1: {}
              example-2: {}
components:
  schemas: {}
