openapi: 3.0.0
info:
  title: Test-car
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /get-transfer:
    get:
      summary: get car
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  year:
                    type: string
                  color:
                    type: integer
              examples:
                example-1:
                  value:
                    name: Hilander
                    color: black
                    year: 2020
        '':
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                example-1:
                  value:
                    data:
                      id: 936f122d-3a66-4460-b0f4-a8f538d00777
                      type: transfer
                      attributes:
                        created_at: '2020-05-13T03:33:57Z'
                        updated_at: '2020-05-13T03:33:57Z'
                        destination_account_number: bongloy_testing-P01-1234560
                        destination_account_holder_name: null
                        currency: USD
                        status: failed
                        metadata:
                          foobar: foobar
                        error_code: destination_account_not_found
                        error_message: Destination account not found
                        amount: 10000
                example-2:
                  value:
                    data:
                      id: 4748f53f-cde5-45dc-92e1-1a7b089921eb
                      type: transfer
                      attributes:
                        created_at: '2020-05-13T03:35:57Z'
                        updated_at: '2020-05-13T03:35:57Z'
                        destination_account_number: bongloy_testing-P01-1234560
                        destination_account_holder_name: null
                        currency: USD
                        status: failed
                        metadata:
                          foobar: foobar
                        error_code: destination_account_not_found
                        error_message: Destination account not found
                        amount: 10
      operationId: get-car
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
        - schema:
            type: string
          in: header
          name: Content-Type
      description: ''
    parameters: []
components:
  schemas: {}
