openapi: 3.0.0
info:
  title: Test-car
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /car:
    get:
      summary: get car
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  year:
                    type: string
                  color:
                    type: integer
              examples:
                example-1:
                  value:
                    name: Hilander
                    color: black
                    year: 2020
      operationId: get-car
components:
  schemas: {}
